### ISSUE TITLE
Add paragraph in README.md introducing what this package is

### ISSUE THREAD

**Issue by consideRatio** [minrk/jupyter-keepalive#6]
I understand this as a jupyter severextension combined with a jupyter labextension, but I've not tried this out myself yet and don't know what to expect when trying it out besides I've heard its meant to help a user keep a server alive from being culled.

It would be good to have a paragraph in the readme introducing the purpose etc, preferably also with a screenshot of any jupyterlab UI if there is any.

**Comment by yuvipanda** [comment]
Done.
